---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Test MicroService API"
host: "3062df15aa.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /test/api/v1/active/:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
securityDefinitions:
  anyName:
    type: "apiKey"
    name: "Unused"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:356612603470:function:publicApiAuthorizationLambda/invocations"
      authorizerResultTtlInSeconds: 0
      type: "request"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
