---
swagger: "2.0"
info:
  description: "MySugr MicroService REST Service"
  version: "1.0.0"
  title: "Test MicroService API"
host: "3062df15aa.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /test/api/v1/active/:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Entitlements"
  /cmi-integration/api/v1/active-users/:
    post:
      operationId: "postActiveUsersUsingPOST"
      parameters:
      - name: "solution"
        in: "path"
        required: true
        type: "string"
      responses:
        "400":
          description: "400 response"
        "204":
          description: "204 response"
    get:
      produces:
      - "application/json"
      parameters:
      - name: "consentId"
        in: "path"
        required: true
        type: "string"
      - name: "accountId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Entitlements"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
        "401":
          description: "401 response"
        "403":
          description: "403 response"
        "415":
          description: "415 response"
        "404":
          description: "404 response"
        "504":
          description: "504 response"
        "405":
          description: "405 response"
        "406":
          description: "406 response"
        "408":
          description: "408 response"
  /cmi-integration/api/v1/active-users/{solution}:
    post:
      operationId: "postActiveUsersUsingPOST"
      parameters:
      - name: "solution"
        in: "path"
        required: true
        type: "string"
      responses:
        "400":
          description: "400 response"
        "204":
          description: "204 response"
    get:
      produces:
      - "application/json"
      parameters:
      - name: "consentId"
        in: "path"
        required: true
        type: "string"
      - name: "accountId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Entitlements"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
        "401":
          description: "401 response"
        "403":
          description: "403 response"
        "415":
          description: "415 response"
        "404":
          description: "404 response"
        "504":
          description: "504 response"
        "405":
          description: "405 response"
        "406":
          description: "406 response"
        "408":
          description: "408 response"
definitions:
  Order:
    type: "object"
    properties:
      header:
        $ref: "#/definitions/OrderHeader"
      items:
        type: "array"
        description: "List of included order items"
        items:
          $ref: "#/definitions/OrderItem"
    description: "Order"
  MODEL8bf0b2:
    type: "object"
  OrderHeader:
    type: "object"
    properties:
      authorizedAmount:
        type: "string"
        description: "Autorized amount, e.g. '31.08.2019'"
      contract:
        type: "string"
        description: "SAP contract number, e.g. '6235000028'"
      custcity:
        type: "string"
        description: "City, e.g. 'Washington'"
      custcountry:
        type: "string"
        description: "Country (ISO 2 Code), e.g. 'ES'"
      custname:
        type: "string"
        description: "Name, e.g. 'John Doe'"
      custpo:
        type: "string"
        description: "Customer purchase order, generated value, e.g. '9999962350'"
      custregion:
        type: "string"
        description: "Region (Province), e.g. 'DC'"
      custstreet:
        type: "string"
        description: "Street, e.g. '1600 Pennsylvania Ave'"
      custzipcode:
        type: "string"
        description: "Zip code, e.g. '12345'"
      doctype:
        type: "string"
        description: "DOCTYPE, e.g. '012b0000000DigLAAS'"
      methodVariant:
        type: "string"
        description: "Payment method variant, e.g. 'VISA'"
      orderCurrency:
        type: "string"
        description: "Order currency, e.g. 'EUR'"
      paymentMethod:
        type: "string"
        description: "Payment methond, e.g. 'Card'"
      periodEnd:
        type: "string"
        description: "Period end, e.g. '31.08.2019'"
      periodStart:
        type: "string"
        description: "Period start, e.g. '01.08.2019'"
      pspProcessingStatus:
        type: "string"
        description: "PSP processing status, e.g. 'AUTHORIZED'"
      pspToken:
        type: "string"
        description: "PSP token, e.g. '1234567890'"
    description: "Order header"
  MODEL0c958a:
    type: "object"
  MODEL0e0e9e:
    type: "object"
    required:
    - "email"
    - "passwordResetLink"
    properties:
      email:
        type: "string"
        description: "The email of the user account"
      passwordResetLink:
        type: "string"
        description: "The reset password link to be included in the body of the email"
  MODELcc4a9f:
    type: "object"
    properties:
      orders:
        type: "array"
        description: "List of included orders"
        items:
          $ref: "#/definitions/Order"
      type:
        type: "string"
        description: "Order type"
    description: "Order JSON object"
  Entitlements:
    type: "object"
    required:
    - "accepted"
    - "available"
    properties:
      accepted:
        type: "array"
        description: "A list of the entitlements a user has accepted"
        items:
          $ref: "#/definitions/items"
      available:
        type: "array"
        description: "A list of the entitlements available to the user"
        items:
          $ref: "#/definitions/items"
    description: "Entitlements Response Object"
  OrderItem:
    type: "object"
    properties:
      material:
        type: "string"
        description: "SAP material number, e.g. '06453970037'"
      qty:
        type: "string"
        description: "Order quantity, e.g. '3'"
      textLine:
        type: "string"
        description: "Text line, e.g. 'Center 1 - DS1'"
      textObject:
        type: "string"
        description: "Text object, e.g. 'ZIPP'"
      totalPrice:
        type: "string"
        description: "Total item price, e.g. '20,99'"
    description: "Order item"
  items:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "number"
      name:
        type: "string"
    description: "Gigya Entitlement Object"
  OrderStatusResponse:
    type: "object"
    properties:
      ids:
        type: "array"
        description: "List of unique Order IDs"
        items:
          type: "string"
      status:
        type: "string"
        description: "Order status"
      type:
        type: "string"
        description: "Order type"
    description: "Order status response"
  MODEL7dcf99:
    type: "object"
    required:
    - "newPassword"
    - "passwordResetToken"
    properties:
      passwordResetToken:
        type: "string"
        description: "The reset password token received in the reset password email"
      newPassword:
        type: "string"
        description: "The user's new password"
