---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Test MicroService API"
host: "3062df15aa.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /test/api/v1/active/:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Entitlements"
